class MailList:
    spam_mail_list = ['newsletter@spikemails.in', 'noreply@shriramgeneral.co.in', 'noreply@medium.com',
                 'digest-noreply@quora.com', 'notification+pkjk_pui@facebookmail.com', 'promo@tradusmailer.in',
                 'Info@ipaidabribe.com', 'noreply@gotradus.com', 'shopping@mailers.irctcshopping.com',
                 'salesupdate@myntra.com', 'thepostmanteam@getpostman.com',
                 'promo@bestshoppers.in', 'welcome@offers.shopcluesmail.com', 'promotions@flipkartmail.com',
                 'RunnersWorldNews@runnersworldnews.delivery.net',
                 'Feedback@goibibopromotions.com', 'newsletter@snapdeal.in', 'mails@freerecharge.net.in',
                 'RunningTimes@runningtimes.delivery.net',
                 'offers@service.couponhaat.com ', 'noreply@freecharge.net.in', 'ecampaign@email.couponhaat.com',
                 'store-news@myntra.com', 'store-news@junglee.com',
                 'RunnersWorldNews@news-runnersworld.com', 'irctctourismoffers@irctc.co.in',
                 'productupdates@tolexomail.com', 'noreply@bmsrv3.amubm.com', 'newsletter@gimailers.com',
                 'Shopclues@offers.shopcluesmail.com', 'Bicycling@bicycling.delivery.net', 'appstore@myntra.com',
                 'info@news.runtastic.com',
                 'service@saleskart.co.in', 'store_news@amazon.in', 'RunnersWorld@runnersworld.delivery.net',
                 'noreply@toscaa.com', 'noreply@amulyammail.com',
                 'support@shop.sdconnect.in', 'shb@shopclues-mailer.com', 'newsletter@crm.jabong.com',
                 'fashion@crm.jabong.com', 'snapdeal@trigger.cxesnapdeal.in',
                 'welcome@shopcluesemail.com', 'style@crm.jabong.com', 'support@shop.cxesnapdeal.in',
                 'notification@airpostmail.in', 'trueman@truecaller.com',
                 'notification@freetalkie.com', 'newsletter@mailers.e-redbus.in', 'etmoney@etmoneymail.com',
                 'no-reply@unocoin.com', 'indianrailways@irctc.co.in',
                 'crm@em.oyorooms.com', 'info@lucifro.com', 'noreply@jobalertshub.com', 'newsletter@gramafones.com',
                 'newsletter@freezoes.com', 'newsletter@grasscross.com', 'info@e.shoponmail.in',
                 'info@bajajfinance.com', 'notification@seajin.chtah.com',
                 'product@etmoney.com', 'supports@ykqu7.healthy-glad.in', 'notifications@kwcd7.online-style.in',
                 'newsletters@shopatbest.com,newsletters@smtpmailbox.com',
                 'notifications@seajin.chtah.com', 'newsletters@consumerconnect.in', 'newsletters@magicmails.in',
                 'info@toscaa.com', 'newsletters@env.readthenotes.com',
                 'newsletters@emailybee.com', 'newsletters@m2i.in', 'newsletters@netengen.com',
                 'newsletters@buzz-india.com', 'noreply@picklemasti.net', 'newsletter@picklemasti.net',
                 'mail@flipkartletters.com', 'runnersworld@eml.hearstmags.com', 'store-news@amazon.in',
                 'online@myntraclub.com', 'newsletter@mortyhardy.com', 'newsletter@autocardoctor.com',
                 'runnersworld@eml.hearstmags.com', 'info@lenskt.com', 'rundown@news-runnersworld.com',
                 'RunnersWorld@em-runnersworld.com', 'info@mc.progressingindia.com',
                 'newsletter@travel.emails-makemytrip.com']